// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuEg97XIMa9v9mAhxRfLrAM2Mji0WZVXw',
    appId: '1:801446275033:web:910dcf4debd1a9c6789bc8',
    messagingSenderId: '801446275033',
    projectId: 'go-cart-d3ceb',
    authDomain: 'go-cart-d3ceb.firebaseapp.com',
    storageBucket: 'go-cart-d3ceb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwA1s1W_KCIeakt_YvQBKiA0556ZvOM3w',
    appId: '1:801446275033:android:47ebc26ae1fcb432789bc8',
    messagingSenderId: '801446275033',
    projectId: 'go-cart-d3ceb',
    storageBucket: 'go-cart-d3ceb.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuEg97XIMa9v9mAhxRfLrAM2Mji0WZVXw',
    appId: '1:801446275033:web:d4b2e248f4961b62789bc8',
    messagingSenderId: '801446275033',
    projectId: 'go-cart-d3ceb',
    authDomain: 'go-cart-d3ceb.firebaseapp.com',
    storageBucket: 'go-cart-d3ceb.firebasestorage.app',
  );
}
